### ISSUE TITLE
Mypy error after project restructure: Module "microvenv._create" has no attribute "main"

### ISSUE THREAD

**Issue by kbaikov** [brettcannon/microvenv#56]
The full error message: microvenv\__main__.py:1: error: Module "microvenv._create" has no attribute "main"  [attr-defined]

Steps to reproduce:

1. clone the project
2. run `nox -s lint`

microvenv\__main__.py:1: error: Module "microvenv._create" has no attribute "main"  [attr-defined]

Full output: 

```nox -s lint
❯ nox -s lint
nox > Running session lint
nox > Creating virtual environment (virtualenv) using python.exe in .nox\lint
nox > python -m pip install '.[lint]'
nox > ruff check .
nox > black --check .
All done! ✨ 🍰 ✨
13 files would be left unchanged.
nox > mypy .
microvenv\__main__.py:1: error: Module "microvenv._create" has no attribute "main"  [attr-defined]
Found 1 error in 1 file (checked 11 source files)
nox > Command mypy . failed with exit code 1
nox > Session lint failed.
```

Versions:
win11 and py312

**Comment by brettcannon** [comment]
Unfortunately I can't reproduce:

```
❯ pipx run nox -s lint
nox > Running session lint
nox > Creating virtual environment (virtualenv) using python in .nox/lint
nox > python -m pip install '.[lint]'
nox > ruff check .
nox > black --check .
All done! ✨ 🍰 ✨
13 files would be left unchanged.
nox > mypy .
Success: no issues found in 11 source files
nox > stubtest microvenv
Success: no issues found in 3 modules
nox > Session lint was successful.
```

This is under Linux with either Python 3.11 or 3.12.

Do you have any global mypy config set?

**Comment by brettcannon** [comment]
And I assume the test suite passes for you?

**Comment by brettcannon** [comment]
Actually, I think I figured out why mypy is complaining; see https://github.com/brettcannon/microvenv/pull/57 for (hopefully) a solution.

**Comment by brettcannon** [comment]
Fixed in https://pypi.org/project/microvenv/2023.4/ .

**Comment by kbaikov** [comment]
Unfortunately this didn't fix it.
I still get the error in the new version.

And to answer you previous questions: Yes, the `nox -s test` passes. No i don't have any global mypy configuration.

I noticed you run it with pipx, may be it does something different?
I just create venv in the just cloned project folder, install nox in there,  and run `nox -s lint`

**Comment by brettcannon** [comment]
> I noticed you run it with pipx, may be it does something different?

I doubt it; pipx just installs a tool and runs it.

Anyway, I was able to reproduce locally.

**Comment by brettcannon** [comment]
@kbaikov Thanks for your patience! I realize part of the issue is the linting on CI was only running under Linux and mypy was not checking from other perspectives. I simply didn't think about the disconnect. 😅

I got everything fixed and pushed a 2023.5 release. I have also updated linting under CI to also run under Windows to help prevent this from happening again.
